"kaleka" => [
  [
    "id" => 1,
    "nama_kaleka" => "Kaleka 1",
    "keterangan" => "",
    "petani" => [
      "nama_lengkap" => "Jito Susilo",
      "nama_panggilan" => "Jito",
      "nik" => "624535345444343",
      "no_kk" => "1234567890123456",
      "jenis_kelamin" => "Pria",
      "tanggal_lahir" => "20 Maret 1991",
      "nomor_hp" => "081234567890",
      "alamat" => "",
      "foto" => "images/petani1.jpeg",
      "status_petani" => "aktif",
      "petani_kelompok" => [
        [
          "nama_kelompok_tani" => "Kelompok 1",
          "kategori_kelompok" => "Kategori 1",
          "is_masyarakat_hukum_adat" => "1",
          "deskripsi" => "Kelompok tani yang aktif dalam kegiatan pertanian di wilayah Kaleka 1",
          "alamat" => "Jalan Raya Tumbang Samui No. 123",
          "akses_perjalanan" => "Mudah",
          "kondisi_jalan" => "Baik",
          "tahun_bentuk" => "2020",
          "nomor_sk" => "SK-001/2020",
          "tanggal_sk" => "15 April 2020",
          "status_kelompok" => "Aktif",
          "jabatan_kelompok" => "Ketua",
          "tahun_gabung" => "2026",
          "tanggal_keluar" => "2024",
          "is_pengurus" => "1",
          "is_active" => "1"
        ],
        [
          "nama_kelompok_tani" => "Kelompok 2",
          "kategori_kelompok" => "Kategori 2",
          "is_masyarakat_hukum_adat" => "0",
          "deskripsi" => "Kelompok tani yang baru dibentuk dan sedang dalam tahap pengembangan di wilayah Kaleka 1",
          "alamat" => "Jalan Raya Tumbang Samui No. 456",
          "akses_perjalanan" => "Mudah",
          "kondisi_jalan" => "Baik",
          "tahun_bentuk" => "2021",
          "nomor_sk" => "SK-002/2021",
          "tanggal_sk" => "15 April 2021",
          "status_kelompok" => "Aktif",
          "jabatan_kelompok" => "Anggota",
          "tahun_gabung" => "2026",
          "tanggal_keluar" => "2024",
          "is_pengurus" => "1",
          "is_active" => "1"
        ],
      ],
    ],
    "desa" => [
      "nama_desa" => "Tumbang Samui",
      "tipe_wilayah" => "kelurahan",
      "nama_kecamatan" => "Manuhing Raya",
      "nama_kabupaten" => "Gunung Mas",
      "tipe" => "kabupaten",
      "nama_provinsi" => "Kalimantan Tengah",
      "kode_pos" => "74562",
    ],
    "tanah" => [
      "nama_lahan" => "Lahan keluarga",
      "legalitas_lahan" => "Belum Ada",
      "status_kawasan" => "Kaleka",
      "luas_ha" => "±1 Ha",
      "centroid_lat" => "-1.2719",
      "centroid_lng" => "113.3210",
      "geom_area" => [
        [-1.2716, 113.3208],
        [-1.2719, 113.3210],
        [-1.2721, 113.3206],
        [-1.2717, 113.3204]
      ],
      "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
      "keterangan" => "",
      "sudah_validasi" => "Sudah",
      "tanggal_validasi" => "15 April 2025",
      "sejarah" => "Lahan keluarga",
    ],
    "perairan_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "warna_air" => "Biru",
      "jenis_palung" => "Palung alami",
      "kecepatan_aliran" => "Sedang",
      "kedalaman_cm" => "120",
      "lebar_m" => "30",
      "debit_lps" => "500",
      "ph" => "7.5",
      "kekeruhan_ntu" => "10",
      "catatan" => "Perairan dalam kondisi baik dengan aliran sedang dan kedalaman yang cukup untuk pertanian.",
    ],
    "infrastruktur_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "akses_perjalanan" => "Mudah",
      "kondisi_jalan" => "Baik",
      "jarak_ke_jalan_km" => "0.5",
      "ada_jembatan" => "Ya",
      "ada_listrik" => "Ya",
      "ada_internet" => "Ya",
      "sinyal_seluler" => "Sangat Baik",
      "catatan" => "Infrastruktur di wilayah ini sangat baik dan mendukung kebutuhan masyarakat.",
    ],
    "land_cover_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "kategori_area" => "Pertanian",
      "penggunaan_pertanian" => "Padi",
      "penggunaan_lainnya" => "Pemukiman",
      "persentase_tutupan" => "70%",
      "catatan" => "Mayoritas lahan digunakan untuk pertanian padi dengan beberapa area pemukiman di sekitarnya.",
    ],
    "topografi_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "lanskap" => "Datar",
      "fitur_tambahan" => "Terdapat lembah kecil",
      "elevasi_mdpl" => "200 mdpl",
      "kemiringan_derajat" => "1.5",
      "rawan_erosi" => "Tidak Rawan",
      "arah_lereng" => "Utara",
      "catatan" => "Topografi datar dengan kemiringan yang rendah, cocok untuk pertanian dan tidak rawan erosi.",
    ],
    "pohon_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "nama_pohon" => "Mangga",
      "nama_latin" => "Mangifera indica",
      "fungsi_pohon" => "Penghasil buah dan pohon bayangan",
      "jumlah_pohon" => "5",
      "diameter_rata2_cm" => "30",
      "tinggi_rata2_m" => "4",
      "kondisi" => "Baik",
      "catatan" => "Pohon mangga dalam kondisi baik dan sehat.",
    ],
    "bank_benih" => [
      [
        "nomor_aksesi" => "842342345",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Panamaea americana",
        "nama_ilmiah" => "American Panamaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Amerika",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "12 Maret 2025",
        "jumlah_stok" => "12",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "90%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "12 Maret 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih berkualitas tinggi",
      ],
      [
        "nomor_aksesi" => "742342346",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Kacang Tanah",
        "nama_ilmiah" => "Arachis hypogaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Indonesia",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "15 April 2025",
        "jumlah_stok" => "20",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "95%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "15 April 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih kacang tanah berkualitas tinggi",
      ],
    ],
  ],
  [
    "id" => 2,
    "nama_kaleka" => "Kaleka 2",
    "keterangan" => "",
    "petani" => [
      "nama_lengkap" => "Sumarno",
      "nama_panggilan" => "Sumarno",
      "nik" => "624535345444343",
      "no_kk" => "1234567890123456",
      "jenis_kelamin" => "Pria",
      "tanggal_lahir" => "23 April 1990",
      "nomor_hp" => "082134567833",
      "alamat" => "",
      "foto" => "images/petani2.jpeg",
      "status_petani" => "aktif",
      "petani_kelompok" => [
        [
          "nama_kelompok_tani" => "Kelompok 2",
          "kategori_kelompok" => "Kategori 2",
          "is_masyarakat_hukum_adat" => "1",
          "deskripsi" => "Kelompok tani yang aktif dalam kegiatan pertanian di wilayah Kaleka 2",
          "alamat" => "Jalan Raya Tumbang Samui No. 456",
          "akses_perjalanan" => "Mudah",
          "kondisi_jalan" => "Baik",
          "tahun_bentuk" => "2020",
          "nomor_sk" => "SK-002/2020",
          "tanggal_sk" => "15 Mei 2020",
          "status_kelompok" => "Aktif",
          "jabatan_kelompok" => "Ketua",
          "tahun_gabung" => "2025",
          "tanggal_keluar" => "2024",
          "is_pengurus" => "1",
          "is_active" => "1"
        ],
      ],
    ],
    "desa" => [
      "nama_desa" => "Tumbang Samui",
      "tipe_wilayah" => "kelurahan",
      "nama_kecamatan" => "Manuhing Raya",
      "nama_kabupaten" => "Gunung Mas",
      "tipe" => "kabupaten",
      "nama_provinsi" => "Kalimantan Tengah",
      "kode_pos" => "74562",
    ],
    "tanah" => [
      "nama_lahan" => "Lahan keluarga",
      "legalitas_lahan" => "Belum Ada",
      "status_kawasan" => "Kaleka",
      "luas_ha" => "±1 Ha",
      "centroid_lat" => "-1.2963889949807585",
      "centroid_lng" => "113.31212997436525",
      "geom_area" => [
        [-1.2971025312497146, 113.311185836792],
        [-1.2965662268502558, 113.3118510246277],
        [-1.296952366029318, 113.31223726272584],
      ],
      "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
      "keterangan" => "",
      "sudah_validasi" => "Sudah",
      "tanggal_validasi" => "15 April 2025",
      "sejarah" => "Lahan keluarga",
    ],
    "perairan_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "warna_air" => "Biru",
      "jenis_palung" => "Palung alami",
      "kecepatan_aliran" => "Sedang",
      "kedalaman_cm" => "120",
      "lebar_m" => "30",
      "debit_lps" => "500",
      "ph" => "7.5",
      "kekeruhan_ntu" => "10",
      "catatan" => "Perairan dalam kondisi baik dengan aliran sedang dan kedalaman yang cukup untuk pertanian.",
    ],
    "infrastruktur_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "akses_perjalanan" => "Mudah",
      "kondisi_jalan" => "Baik",
      "jarak_ke_jalan_km" => "0.5",
      "ada_jembatan" => "Ya",
      "ada_listrik" => "Ya",
      "ada_internet" => "Ya",
      "sinyal_seluler" => "Sangat Baik",
      "catatan" => "Infrastruktur di wilayah ini sangat baik dan mendukung kebutuhan masyarakat.",
    ],
    "land_cover_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "kategori_area" => "Pertanian",
      "penggunaan_pertanian" => "Padi",
      "penggunaan_lainnya" => "Pemukiman",
      "persentase_tutupan" => "70%",
      "catatan" => "Mayoritas lahan digunakan untuk pertanian padi dengan beberapa area pemukiman di sekitarnya.",
    ],
    "topografi_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "lanskap" => "Datar",
      "fitur_tambahan" => "Terdapat lembah kecil",
      "elevasi_mdpl" => "200 mdpl",
      "kemiringan_derajat" => "1.5",
      "rawan_erosi" => "Tidak Rawan",
      "arah_lereng" => "Utara",
      "catatan" => "Topografi datar dengan kemiringan yang rendah, cocok untuk pertanian dan tidak rawan erosi.",
    ],
    "pohon_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "nama_pohon" => "Mangga",
      "nama_latin" => "Mangifera indica",
      "fungsi_pohon" => "Penghasil buah dan pohon bayangan",
      "jumlah_pohon" => "5",
      "diameter_rata2_cm" => "30",
      "tinggi_rata2_m" => "4",
      "kondisi" => "Baik",
      "catatan" => "Pohon mangga dalam kondisi baik dan sehat.",
    ],
    "bank_benih" => [
      [
        "nomor_aksesi" => "842342345",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Panamaea americana",
        "nama_ilmiah" => "American Panamaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Amerika",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "12 Maret 2025",
        "jumlah_stok" => "12",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "90%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "12 Maret 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih berkualitas tinggi",
      ],
      [
        "nomor_aksesi" => "742342346",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Kacang Tanah",
        "nama_ilmiah" => "Arachis hypogaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Indonesia",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "15 April 2025",
        "jumlah_stok" => "20",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "95%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "15 April 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih kacang tanah berkualitas tinggi",
      ],
    ],
  ],
  [
    "id" => 3,
    "nama_kaleka" => "Kaleka 3",
    "keterangan" => "",
    "petani" => [
      "nama_lengkap" => "Sumarno",
      "nama_panggilan" => "Sumarno",
      "nik" => "624535345444343",
      "no_kk" => "1234567890123456",
      "jenis_kelamin" => "Pria",
      "tanggal_lahir" => "23 April 1990",
      "nomor_hp" => "082134567833",
      "alamat" => "",
      "foto" => "images/petani3.jpeg",
      "status_petani" => "aktif",
      "petani_kelompok" => [
        [
          "nama_kelompok_tani" => "Kelompok 2",
          "kategori_kelompok" => "Kategori 2",
          "is_masyarakat_hukum_adat" => "1",
          "deskripsi" => "Kelompok tani yang aktif dalam kegiatan pertanian di wilayah Kaleka 2",
          "alamat" => "Jalan Raya Tumbang Samui No. 456",
          "akses_perjalanan" => "Mudah",
          "kondisi_jalan" => "Baik",
          "tahun_bentuk" => "2020",
          "nomor_sk" => "SK-002/2020",
          "tanggal_sk" => "15 Mei 2020",
          "status_kelompok" => "Aktif",
          "jabatan_kelompok" => "Ketua",
          "tahun_gabung" => "2025",
          "tanggal_keluar" => "2024",
          "is_pengurus" => "1",
          "is_active" => "1"
        ],
      ],
    ],
    "desa" => [
      "nama_desa" => "Tumbang Samui",
      "tipe_wilayah" => "kelurahan",
      "nama_kecamatan" => "Manuhing Raya",
      "nama_kabupaten" => "Gunung Mas",
      "tipe" => "kabupaten",
      "nama_provinsi" => "Kalimantan Tengah",
      "kode_pos" => "74562",
    ],
    "tanah" => [
      "nama_lahan" => "Lahan keluarga",
      "legalitas_lahan" => "Belum Ada",
      "status_kawasan" => "Kaleka",
      "luas_ha" => "±1 Ha",
      "centroid_lat" => "-1.2963889949807585",
      "centroid_lng" => "113.31212997436525",
      "geom_area" => [
        [-1.2963889949807585, 113.31212997436525],
        [-1.2962710079893713, 113.31307411193849],
        [-1.297139821160766, 113.31357836723329],
        [-1.2970861907267195, 113.31277370452882],
      ],
      "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
      "keterangan" => "",
      "sudah_validasi" => "Sudah",
      "tanggal_validasi" => "15 April 2025",
      "sejarah" => "Lahan keluarga",
    ],
    "perairan_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "warna_air" => "Biru",
      "jenis_palung" => "Palung alami",
      "kecepatan_aliran" => "Sedang",
      "kedalaman_cm" => "120",
      "lebar_m" => "30",
      "debit_lps" => "500",
      "ph" => "7.5",
      "kekeruhan_ntu" => "10",
      "catatan" => "Perairan dalam kondisi baik dengan aliran sedang dan kedalaman yang cukup untuk pertanian.",
    ],
    "infrastruktur_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "akses_perjalanan" => "Mudah",
      "kondisi_jalan" => "Baik",
      "jarak_ke_jalan_km" => "0.5",
      "ada_jembatan" => "Ya",
      "ada_listrik" => "Ya",
      "ada_internet" => "Ya",
      "sinyal_seluler" => "Sangat Baik",
      "catatan" => "Infrastruktur di wilayah ini sangat baik dan mendukung kebutuhan masyarakat.",
    ],
    "land_cover_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "kategori_area" => "Pertanian",
      "penggunaan_pertanian" => "Padi",
      "penggunaan_lainnya" => "Pemukiman",
      "persentase_tutupan" => "70%",
      "catatan" => "Mayoritas lahan digunakan untuk pertanian padi dengan beberapa area pemukiman di sekitarnya.",
    ],
    "topografi_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "lanskap" => "Datar",
      "fitur_tambahan" => "Terdapat lembah kecil",
      "elevasi_mdpl" => "200 mdpl",
      "kemiringan_derajat" => "1.5",
      "rawan_erosi" => "Tidak Rawan",
      "arah_lereng" => "Utara",
      "catatan" => "Topografi datar dengan kemiringan yang rendah, cocok untuk pertanian dan tidak rawan erosi.",
    ],
    "pohon_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "nama_pohon" => "Mangga",
      "nama_latin" => "Mangifera indica",
      "fungsi_pohon" => "Penghasil buah dan pohon bayangan",
      "jumlah_pohon" => "5",
      "diameter_rata2_cm" => "30",
      "tinggi_rata2_m" => "4",
      "kondisi" => "Baik",
      "catatan" => "Pohon mangga dalam kondisi baik dan sehat.",
    ],
    "bank_benih" => [
      [
        "nomor_aksesi" => "842342345",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Panamaea americana",
        "nama_ilmiah" => "American Panamaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Amerika",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "12 Maret 2025",
        "jumlah_stok" => "12",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "90%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "12 Maret 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih berkualitas tinggi",
      ],
      [
        "nomor_aksesi" => "742342346",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Kacang Tanah",
        "nama_ilmiah" => "Arachis hypogaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Indonesia",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "15 April 2025",
        "jumlah_stok" => "20",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "95%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "15 April 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih kacang tanah berkualitas tinggi",
      ],
    ],
  ],
  [
    "id" => 4,
    "nama_kaleka" => "Kaleka 4",
    "keterangan" => "",
    "petani" => [
      "nama_lengkap" => "Sumarno",
      "nama_panggilan" => "Sumarno",
      "nik" => "624535345444343",
      "no_kk" => "1234567890123456",
      "jenis_kelamin" => "Pria",
      "tanggal_lahir" => "23 April 1990",
      "nomor_hp" => "082134567833",
      "alamat" => "",
      "foto" => "images/petani4.jpeg",
      "status_petani" => "aktif",
      "petani_kelompok" => [
        [
          "nama_kelompok_tani" => "Kelompok 2",
          "kategori_kelompok" => "Kategori 2",
          "is_masyarakat_hukum_adat" => "1",
          "deskripsi" => "Kelompok tani yang aktif dalam kegiatan pertanian di wilayah Kaleka 2",
          "alamat" => "Jalan Raya Tumbang Samui No. 456",
          "akses_perjalanan" => "Mudah",
          "kondisi_jalan" => "Baik",
          "tahun_bentuk" => "2020",
          "nomor_sk" => "SK-002/2020",
          "tanggal_sk" => "15 Mei 2020",
          "status_kelompok" => "Aktif",
          "jabatan_kelompok" => "Ketua",
          "tahun_gabung" => "2025",
          "tanggal_keluar" => "2024",
          "is_pengurus" => "1",
          "is_active" => "1"
        ],
      ],
    ],
    "desa" => [
      "nama_desa" => "Tumbang Samui",
      "tipe_wilayah" => "kelurahan",
      "nama_kecamatan" => "Manuhing Raya",
      "nama_kabupaten" => "Gunung Mas",
      "tipe" => "kabupaten",
      "nama_provinsi" => "Kalimantan Tengah",
      "kode_pos" => "74562",
    ],
    "tanah" => [
      "nama_lahan" => "Lahan keluarga",
      "legalitas_lahan" => "Belum Ada",
      "status_kawasan" => "Kaleka",
      "luas_ha" => "±1 Ha",
      "centroid_lat" => "-1.2963889949807585",
      "centroid_lng" => "113.31212997436525",
      "geom_area" => [
        [-1.2950160551044538, 113.31307411193849],
        [-1.2960028557157703, 113.31398606300355],
        [-1.296027911195035, 113.31515550613405],
        [-1.2953005480171402, 113.31549882888795],
        [-1.2947693548915822, 113.31483364105226],
      ],
      "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
      "keterangan" => "",
      "sudah_validasi" => "Sudah",
      "tanggal_validasi" => "15 April 2025",
      "sejarah" => "Lahan keluarga",
    ],
    "perairan_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "warna_air" => "Biru",
      "jenis_palung" => "Palung alami",
      "kecepatan_aliran" => "Sedang",
      "kedalaman_cm" => "120",
      "lebar_m" => "30",
      "debit_lps" => "500",
      "ph" => "7.5",
      "kekeruhan_ntu" => "10",
      "catatan" => "Perairan dalam kondisi baik dengan aliran sedang dan kedalaman yang cukup untuk pertanian.",
    ],
    "infrastruktur_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "akses_perjalanan" => "Mudah",
      "kondisi_jalan" => "Baik",
      "jarak_ke_jalan_km" => "0.5",
      "ada_jembatan" => "Ya",
      "ada_listrik" => "Ya",
      "ada_internet" => "Ya",
      "sinyal_seluler" => "Sangat Baik",
      "catatan" => "Infrastruktur di wilayah ini sangat baik dan mendukung kebutuhan masyarakat.",
    ],
    "land_cover_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "kategori_area" => "Pertanian",
      "penggunaan_pertanian" => "Padi",
      "penggunaan_lainnya" => "Pemukiman",
      "persentase_tutupan" => "70%",
      "catatan" => "Mayoritas lahan digunakan untuk pertanian padi dengan beberapa area pemukiman di sekitarnya.",
    ],
    "topografi_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "lanskap" => "Datar",
      "fitur_tambahan" => "Terdapat lembah kecil",
      "elevasi_mdpl" => "200 mdpl",
      "kemiringan_derajat" => "1.5",
      "rawan_erosi" => "Tidak Rawan",
      "arah_lereng" => "Utara",
      "catatan" => "Topografi datar dengan kemiringan yang rendah, cocok untuk pertanian dan tidak rawan erosi.",
    ],
    "pohon_observasi" => [
      "periode_pengecekan" => "15 April 2025",
      "nama_pohon" => "Mangga",
      "nama_latin" => "Mangifera indica",
      "fungsi_pohon" => "Penghasil buah dan pohon bayangan",
      "jumlah_pohon" => "5",
      "diameter_rata2_cm" => "30",
      "tinggi_rata2_m" => "4",
      "kondisi" => "Baik",
      "catatan" => "Pohon mangga dalam kondisi baik dan sehat.",
    ],
    "bank_benih" => [
      [
        "nomor_aksesi" => "842342345",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Panamaea americana",
        "nama_ilmiah" => "American Panamaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Amerika",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "12 Maret 2025",
        "jumlah_stok" => "12",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "90%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "12 Maret 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih berkualitas tinggi",
      ],
      [
        "nomor_aksesi" => "742342346",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Kacang Tanah",
        "nama_ilmiah" => "Arachis hypogaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Indonesia",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "15 April 2025",
        "jumlah_stok" => "20",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "95%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "15 April 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih kacang tanah berkualitas tinggi",
      ],
    ],
  ],
],