<?php
header('Content-Type: application/json');

echo json_encode([
  "hutan_adat" => [
    [
      "id" => 1,
      "nama_hutan_adat" => "Hutan Adat 1",
      "desa" => [
        "nama_desa" => "Tumbang Samui",
        "tipe_wilayah" => "kelurahan",
        "nama_kecamatan" => "Manuhing Raya",
        "nama_kabupaten" => "Gunung Mas",
        "tipe" => "kabupaten",
        "nama_provinsi" => "Kalimantan Tengah",
        "kode_pos" => "74562",
      ],
      "nomor_sk" => "SK-001/2020",
      "tanggal_sk" => "15 April 2020",
      "status_kawasan" => "KSA",
      "kelompok_tani" => [
        "nama_kelompok_tani" => "MHA 1",
        "kategori_kelompok" => "Kategori Adat 1",
        "deskripsi" => "Masyarakat Hukum Adat yang Aktif dalam kegiatan pertanian di wilayah 1",
        "alamat" => "Jalan Raya Tumbang Samui No. 123",
        "tahun_bentuk" => "2020",
        "nomor_sk" => "SK-001/2020",
        "tanggal_sk" => "15 April 2020",
        "status_kelompok" => "Aktif",
        "total_anggota" => 25,
        "petani_kelompok" => [
          [
            "petani" => [
              "nama_lengkap" => "Jito Susilo",
              "nama_panggilan" => "Jito",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "20 Maret 1991",
              "umur" => "32 tahun",
              "nomor_hp" => "081234567890",
              "alamat" => "Jalan Raya Tumbang Samui No. 123",
              "foto" => "images/petani1.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Ketua",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
          [
            "petani" => [
              "nama_lengkap" => "Gusti Mahendar",
              "nama_panggilan" => "Hendar",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "23 April 1990",
              "umur" => "35 tahun",
              "nomor_hp" => "082134567833",
              "alamat" => "Jalan Raya Tumbang Samui No. 456",
              "foto" => "images/petani4.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
        ],
      ],
      "tanah" => [
        "nama_lahan" => "Lahan keluarga",
        "legalitas_lahan" => "Belum Ada",
        "status_kawasan" => "Hutan Adat",
        "luas_ha" => "±1 Ha",
        "centroid_lat" => "-1.2719",
        "centroid_lng" => "113.3210",
        "geom_area" => [
          [-1.2709, 113.3204],
          [-1.2718, 113.3221],
          [-1.2732, 113.3210],
          [-1.2728, 113.3188],
          [-1.2711, 113.3185]
        ],
        "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
        "keterangan" => "Lahan milik keluarga Jito Susilo yang digunakan untuk pertanian dan kegiatan lainnya.",
        "sudah_validasi" => "Sudah",
        "tanggal_validasi" => "15 April 2025",
        "sejarah" => "Lahan keluarga",
      ],
    ],
    [
      "id" => 2,
      "nama_hutan_adat" => "Hutan Adat 2",
      "desa" => [
        "nama_desa" => "Tumbang Samui",
        "tipe_wilayah" => "kelurahan",
        "nama_kecamatan" => "Manuhing Raya",
        "nama_kabupaten" => "Gunung Mas",
        "tipe" => "kabupaten",
        "nama_provinsi" => "Kalimantan Tengah",
        "kode_pos" => "74562",
      ],
      "nomor_sk" => "SK-002/2021",
      "tanggal_sk" => "15 April 2021",
      "status_kawasan" => "APL",
      "kelompok_tani" => [
        "nama_kelompok_tani" => "MHA 2",
        "kategori_kelompok" => "Kategori Adat 2",
        "deskripsi" => "Masyarakat Hukum Adat yang Aktif dalam kegiatan pertanian di wilayah 2",
        "alamat" => "Jalan Raya Tumbang Samui No. 123",
        "tahun_bentuk" => "2019",
        "nomor_sk" => "SK-001/2019",
        "tanggal_sk" => "25 Mei 2019",
        "status_kelompok" => "Aktif",
        "total_anggota" => 30,
        "petani_kelompok" => [
          [
            "petani" => [
              "nama_lengkap" => "Jito Susilo",
              "nama_panggilan" => "Jito",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "20 Maret 1991",
              "umur" => "32 tahun",
              "nomor_hp" => "081234567890",
              "alamat" => "Jalan Raya Tumbang Samui No. 123",
              "foto" => "images/petani1.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "0",
            "is_active" => "1"
          ],
          [
            "petani" => [
              "nama_lengkap" => "Susanti",
              "nama_panggilan" => "Susanti",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "23 April 1990",
              "umur" => "35 tahun",
              "nomor_hp" => "082134567833",
              "alamat" => "Jalan Raya Tumbang Samui No. 456",
              "foto" => "images/petani2.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Ketua",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
          [
            "petani" => [
              "nama_lengkap" => "Gusti Mahendar",
              "nama_panggilan" => "Hendar",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "23 April 1990",
              "umur" => "35 tahun",
              "nomor_hp" => "082134567833",
              "alamat" => "Jalan Raya Tumbang Samui No. 456",
              "foto" => "images/petani4.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "0",
            "is_active" => "1"
          ],
        ],
      ],
      "tanah" => [
        "nama_lahan" => "Lahan keluarga",
        "legalitas_lahan" => "Belum Ada",
        "status_kawasan" => "Hutan Adat",
        "luas_ha" => "±1 Ha",
        "centroid_lat" => "-1.2719",
        "centroid_lng" => "113.3210",
        "geom_area" => [
          [-1.2851, 113.3351],
          [-1.2860, 113.3372],
          [-1.2881, 113.3364],
          [-1.2874, 113.3338]
        ],
        "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
        "keterangan" => "Lahan milik keluarga Jito Susilo yang digunakan untuk pertanian dan kegiatan lainnya.",
        "sudah_validasi" => "Sudah",
        "tanggal_validasi" => "15 April 2025",
        "sejarah" => "Lahan keluarga",
      ],
    ],
    [
      "id" => 3,
      "nama_hutan_adat" => "Hutan Adat 3",
      "desa" => [
        "nama_desa" => "Tumbang Samui",
        "tipe_wilayah" => "kelurahan",
        "nama_kecamatan" => "Manuhing Raya",
        "nama_kabupaten" => "Gunung Mas",
        "tipe" => "kabupaten",
        "nama_provinsi" => "Kalimantan Tengah",
        "kode_pos" => "74562",
      ],
      "nomor_sk" => "SK-003/2021",
      "tanggal_sk" => "15 Juni 2021",
      "status_kawasan" => "KSA",
      "kelompok_tani" => [
        "nama_kelompok_tani" => "MHA 3",
        "kategori_kelompok" => "Kategori Adat 3",
        "deskripsi" => "Masyarakat Hukum Adat yang Aktif dalam kegiatan pertanian di wilayah 3",
        "alamat" => "Jalan Raya Tumbang Samui No. 123",
        "tahun_bentuk" => "2019",
        "nomor_sk" => "SK-001/2019",
        "tanggal_sk" => "25 Mei 2019",
        "status_kelompok" => "Aktif",
        "total_anggota" => 30,
        "petani_kelompok" => [
          [
            "petani" => [
              "nama_lengkap" => "Jito Susilo",
              "nama_panggilan" => "Jito",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "20 Maret 1991",
              "umur" => "32 tahun",
              "nomor_hp" => "081234567890",
              "alamat" => "Jalan Raya Tumbang Samui No. 123",
              "foto" => "images/petani1.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "0",
            "is_active" => "1"
          ],
          [
            "petani" => [
              "nama_lengkap" => "Susanti",
              "nama_panggilan" => "Susanti",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "23 April 1990",
              "umur" => "35 tahun",
              "nomor_hp" => "082134567833",
              "alamat" => "Jalan Raya Tumbang Samui No. 456",
              "foto" => "images/petani2.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Ketua",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
          [
            "petani" => [
              "nama_lengkap" => "Gusti Mahendar",
              "nama_panggilan" => "Hendar",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "23 April 1990",
              "umur" => "35 tahun",
              "nomor_hp" => "082134567833",
              "alamat" => "Jalan Raya Tumbang Samui No. 456",
              "foto" => "images/petani4.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "0",
            "is_active" => "1"
          ],
        ],
      ],
      "tanah" => [
        "nama_lahan" => "Lahan keluarga",
        "legalitas_lahan" => "Belum Ada",
        "status_kawasan" => "Hutan Adat",
        "luas_ha" => "±1 Ha",
        "centroid_lat" => "-1.2719",
        "centroid_lng" => "113.3210",
        "geom_area" => [
          [-1.2955, 113.3125],
          [-1.2968, 113.3144],
          [-1.2989, 113.3131],
          [-1.2973, 113.3106]
        ],
        "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
        "keterangan" => "Lahan milik keluarga Jito Susilo yang digunakan untuk pertanian dan kegiatan lainnya.",
        "sudah_validasi" => "Sudah",
        "tanggal_validasi" => "15 April 2025",
        "sejarah" => "Lahan keluarga",
      ],
      "kaleka_info" => [
        [
          "id_kaleka" => 2,
          "nama_kaleka" => "Kaleka 2",
          "desa" => [
            "nama_desa" => "Tumbang Samui",
            "nama_kecamatan" => "Manuhing Raya",
            "nama_kabupaten" => "Gunung Mas",
          ],
          "tanah" => [
            "luas_ha" => "±1 Ha",
            "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
          ],
        ],
        [
          "id_kaleka" => 3,
          "nama_kaleka" => "Kaleka 3",
          "desa" => [
            "nama_desa" => "Tumbang Samui",
            "nama_kecamatan" => "Manuhing Raya",
            "nama_kabupaten" => "Gunung Mas",
          ],
          "tanah" => [
            "luas_ha" => "±1 Ha",
            "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
          ],
        ],
      ],
      "benih_info" => [
        [
          "bank_benih" => [
            "id_bank_benih" => "1",
            "nama_lokal" => "Panamaea americana",
            "nama_ilmiah" => "American Panamaea",
            "tanah" => [
              "luas_ha" => "±1 Ha",
              "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
            ],
          ],
        ],
      ],
    ],
    [
      "id" => 4,
      "nama_hutan_adat" => "Hutan Adat 4",
      "desa" => [
        "nama_desa" => "Tumbang Samui",
        "tipe_wilayah" => "kelurahan",
        "nama_kecamatan" => "Manuhing Raya",
        "nama_kabupaten" => "Gunung Mas",
        "tipe" => "kabupaten",
        "nama_provinsi" => "Kalimantan Tengah",
        "kode_pos" => "74562",
      ],
      "nomor_sk" => "SK-004/2021",
      "tanggal_sk" => "21 Maret 2021",
      "status_kawasan" => "APL",
      "kelompok_tani" => [
        "nama_kelompok_tani" => "MHA 4",
        "kategori_kelompok" => "Kategori Adat 4",
        "deskripsi" => "Masyarakat Hukum Adat yang Aktif dalam kegiatan pertanian di wilayah 4",
        "alamat" => "Jalan Raya Tumbang Samui No. 123",
        "tahun_bentuk" => "2020",
        "nomor_sk" => "SK-001/2020",
        "tanggal_sk" => "15 April 2020",
        "status_kelompok" => "Aktif",
        "total_anggota" => 25,
        "petani_kelompok" => [
          [
            "petani" => [
              "nama_lengkap" => "Jito Susilo",
              "nama_panggilan" => "Jito",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "20 Maret 1991",
              "umur" => "32 tahun",
              "nomor_hp" => "081234567890",
              "alamat" => "Jalan Raya Tumbang Samui No. 123",
              "foto" => "images/petani1.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Ketua",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
          [
            "petani" => [
              "nama_lengkap" => "Gusti Mahendar",
              "nama_panggilan" => "Hendar",
              "nik" => "624535345444343",
              "no_kk" => "1234567890123456",
              "jenis_kelamin" => "Pria",
              "tanggal_lahir" => "23 April 1990",
              "umur" => "35 tahun",
              "nomor_hp" => "082134567833",
              "alamat" => "Jalan Raya Tumbang Samui No. 456",
              "foto" => "images/petani4.jpeg",
              "status_petani" => "Aktif",
            ],
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
        ],
      ],
      "tanah" => [
        "nama_lahan" => "Lahan keluarga",
        "legalitas_lahan" => "Belum Ada",
        "status_kawasan" => "Hutan Adat",
        "luas_ha" => "±1 Ha",
        "centroid_lat" => "-1.2719",
        "centroid_lng" => "113.3210",
        "geom_area" => [
          [-1.2748499936243638, 113.17244052886964],
          [-1.2749358030658793, 113.18308353424074],
          [-1.2813155259024067, 113.18233251571657],
          [-1.280671956619748, 113.17301988601686],
        ],
        "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
        "keterangan" => "Lahan milik keluarga Jito Susilo yang digunakan untuk pertanian dan kegiatan lainnya.",
        "sudah_validasi" => "Sudah",
        "tanggal_validasi" => "15 April 2025",
        "sejarah" => "Lahan keluarga",
      ],
    ],
  ],

  "kaleka" => [
    [
      "id_kaleka" => 1,
      "nama_kaleka" => "Kaleka 1",
      "keterangan" => "",
      "petani" => [
        "nama_lengkap" => "Jito Susilo",
        "nama_panggilan" => "Jito",
        "nik" => "624535345444343",
        "no_kk" => "1234567890123456",
        "jenis_kelamin" => "Pria",
        "tanggal_lahir" => "20 Maret 1991",
        "umur" => "32 tahun",
        "nomor_hp" => "081234567890",
        "alamat" => "Jalan Raya Tumbang Samui No. 123",
        "foto" => "images/petani1.jpeg",
        "status_petani" => "Aktif",
        "petani_kelompok" => [
          [
            "nama_kelompok_tani" => "Kelompok 1",
            "kategori_kelompok" => "Kategori 1",
            "deskripsi" => "Kelompok tani yang Aktif dalam kegiatan pertanian di wilayah Kaleka 1",
            "alamat" => "Jalan Raya Tumbang Samui No. 123",
            "akses_perjalanan" => "Mudah",
            "kondisi_jalan" => "Baik",
            "tahun_bentuk" => "2020",
            "nomor_sk" => "SK-001/2020",
            "tanggal_sk" => "15 April 2020",
            "status_kelompok" => "Aktif",
            "jabatan_kelompok" => "Ketua",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
          [
            "nama_kelompok_tani" => "Kelompok 2",
            "kategori_kelompok" => "Kategori 2",
            "deskripsi" => "Kelompok tani yang baru dibentuk dan sedang dalam tahap pengembangan di wilayah Kaleka 1",
            "alamat" => "Jalan Raya Tumbang Samui No. 456",
            "akses_perjalanan" => "Mudah",
            "kondisi_jalan" => "Baik",
            "tahun_bentuk" => "2021",
            "nomor_sk" => "SK-002/2021",
            "tanggal_sk" => "15 April 2021",
            "status_kelompok" => "Aktif",
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
        ],
      ],
      "desa" => [
        "nama_desa" => "Tumbang Samui",
        "tipe_wilayah" => "kelurahan",
        "nama_kecamatan" => "Manuhing Raya",
        "nama_kabupaten" => "Gunung Mas",
        "tipe" => "kabupaten",
        "nama_provinsi" => "Kalimantan Tengah",
        "kode_pos" => "74562",
      ],
      "tanah" => [
        "nama_lahan" => "Lahan keluarga",
        "legalitas_lahan" => "Belum Ada",
        "status_kawasan" => "Kaleka",
        "luas_ha" => "±1 Ha",
        "centroid_lat" => "-1.2719",
        "centroid_lng" => "113.3210",
        "geom_area" => [
          [-1.2716, 113.3208],
          [-1.2719, 113.3210],
          [-1.2721, 113.3206],
          [-1.2717, 113.3204]
        ],
        "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
        "keterangan" => "Lahan milik keluarga Jito Susilo yang digunakan untuk pertanian dan kegiatan lainnya.",
        "sudah_validasi" => "Sudah",
        "tanggal_validasi" => "15 April 2025",
        "sejarah" => "Lahan keluarga",
      ],
      "perairan_observasi" => [
        "periode_pengecekan" => "April 2025",
        "warna_air" => "Biru",
        "jenis_palung" => "Palung alami",
        "kecepatan_aliran" => "Sedang",
        "kedalaman_cm" => "120",
        "lebar_m" => "30",
        "debit_lps" => "500",
        "ph" => "7.5",
        "kekeruhan_ntu" => "10",
        "catatan" => "Perairan dalam kondisi baik dengan aliran sedang dan kedalaman yang cukup untuk pertanian.",
      ],
      "infrastruktur_observasi" => [
        "periode_pengecekan" => "April 2025",
        "akses_perjalanan" => "Mudah",
        "kondisi_jalan" => "Baik",
        "jarak_ke_jalan_km" => "0.5",
        "ada_jembatan" => "Ya",
        "ada_listrik" => "Ya",
        "ada_internet" => "Ya",
        "sinyal_seluler" => "Sangat Baik",
        "catatan" => "Infrastruktur di wilayah ini sangat baik dan mendukung kebutuhan masyarakat.",
      ],
      "land_cover_observasi" => [
        "periode_pengecekan" => "April 2025",
        "kategori_area" => "Pertanian",
        "penggunaan_pertanian" => "Padi",
        "penggunaan_lainnya" => "Pemukiman",
        "persentase_tutupan" => "70%",
        "catatan" => "Mayoritas lahan digunakan untuk pertanian padi dengan beberapa area pemukiman di sekitarnya.",
      ],
      "topografi_observasi" => [
        "periode_pengecekan" => "April 2025",
        "lanskap" => "Datar",
        "fitur_tambahan" => "Terdapat lembah kecil",
        "elevasi_mdpl" => "200 mdpl",
        "kemiringan_derajat" => "1.5",
        "rawan_erosi" => "Tidak Rawan",
        "arah_lereng" => "Utara",
        "catatan" => "Topografi datar dengan kemiringan yang rendah, cocok untuk pertanian dan tidak rawan erosi.",
      ],
      "pohon_observasi" => [
        "periode_pengecekan" => "April 2025",
        "nama_pohon" => "Mangga",
        "nama_latin" => "Mangifera indica",
        "fungsi_pohon" => "Penghasil buah dan pohon bayangan",
        "jumlah_pohon" => "5",
        "diameter_rata2_cm" => "30",
        "tinggi_rata2_m" => "4",
        "kondisi" => "Baik",
        "catatan" => "Pohon mangga dalam kondisi baik dan sehat.",
      ],
      "bank_benih" => [
        [
          "nomor_aksesi" => "842342345",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Panamaea americana",
          "nama_ilmiah" => "American Panamaea",
          "famili_tanaman" => "Benih",
          "provenance" => "Amerika",
          "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
          "tanggal_masuk" => "12 Maret 2025",
          "jumlah_stok" => "12",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "8%",
          "viabilitas_persen" => "90%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "12 Maret 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih berkualitas tinggi",
          "jumlah_ditanam" => "12",
          "satuan" => "PCS",
          "jumlah_hidup" => "11",
          "jumlah_mati" => "1",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
        [
          "nomor_aksesi" => "742342346",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Kacang Tanah",
          "nama_ilmiah" => "Arachis hypogaea",
          "famili_tanaman" => "Benih",
          "provenance" => "Indonesia",
          "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
          "tanggal_masuk" => "15 April 2025",
          "jumlah_stok" => "20",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "8%",
          "viabilitas_persen" => "95%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "15 April 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih kacang tanah berkualitas tinggi",
          "jumlah_ditanam" => "12",
          "satuan" => "PCS",
          "jumlah_hidup" => "11",
          "jumlah_mati" => "1",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
      ],
    ],
    [
      "id_kaleka" => 2,
      "nama_kaleka" => "Kaleka 2",
      "keterangan" => "",
      "petani" => [
        "nama_lengkap" => "Susanti",
        "nama_panggilan" => "Susanti",
        "nik" => "624535345444343",
        "no_kk" => "1234567890123456",
        "jenis_kelamin" => "Pria",
        "tanggal_lahir" => "23 April 1990",
        "umur" => "35 tahun",
        "nomor_hp" => "082134567833",
        "alamat" => "Jalan Raya Tumbang Samui No. 456",
        "foto" => "images/petani2.jpeg",
        "status_petani" => "Aktif",
        "petani_kelompok" => [
          [
            "nama_kelompok_tani" => "Kelompok 2",
            "kategori_kelompok" => "Kategori 2",
            "deskripsi" => "Kelompok tani yang Aktif dalam kegiatan pertanian di wilayah Kaleka 2",
            "alamat" => "Jalan Raya Tumbang Samui No. 456",
            "akses_perjalanan" => "Mudah",
            "kondisi_jalan" => "Baik",
            "tahun_bentuk" => "2020",
            "nomor_sk" => "SK-002/2020",
            "tanggal_sk" => "15 Mei 2020",
            "status_kelompok" => "Aktif",
            "jabatan_kelompok" => "Ketua",
            "tahun_gabung" => "2025",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
        ],
      ],
      "desa" => [
        "nama_desa" => "Tumbang Samui",
        "tipe_wilayah" => "kelurahan",
        "nama_kecamatan" => "Manuhing Raya",
        "nama_kabupaten" => "Gunung Mas",
        "tipe" => "kabupaten",
        "nama_provinsi" => "Kalimantan Tengah",
        "kode_pos" => "74562",
      ],
      "tanah" => [
        "nama_lahan" => "Lahan keluarga",
        "legalitas_lahan" => "Belum Ada",
        "status_kawasan" => "Kaleka",
        "luas_ha" => "±1 Ha",
        "centroid_lat" => "-1.2963889949807585",
        "centroid_lng" => "113.31212997436525",
        "geom_area" => [
          [-1.2971025312497146, 113.311185836792],
          [-1.2965662268502558, 113.3118510246277],
          [-1.296952366029318, 113.31223726272584],
        ],
        "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
        "keterangan" => "Lahan milik keluarga Susanti yang digunakan untuk pertanian dan kegiatan lainnya.",
        "sudah_validasi" => "Sudah",
        "tanggal_validasi" => "15 April 2025",
        "sejarah" => "Lahan keluarga",
      ],
      "perairan_observasi" => [
        "periode_pengecekan" => "April 2025",
        "warna_air" => "Biru",
        "jenis_palung" => "Palung alami",
        "kecepatan_aliran" => "Sedang",
        "kedalaman_cm" => "120",
        "lebar_m" => "30",
        "debit_lps" => "500",
        "ph" => "7.5",
        "kekeruhan_ntu" => "10",
        "catatan" => "Perairan dalam kondisi baik dengan aliran sedang dan kedalaman yang cukup untuk pertanian.",
      ],
      "infrastruktur_observasi" => [
        "periode_pengecekan" => "April 2025",
        "akses_perjalanan" => "Mudah",
        "kondisi_jalan" => "Baik",
        "jarak_ke_jalan_km" => "0.5",
        "ada_jembatan" => "Ya",
        "ada_listrik" => "Ya",
        "ada_internet" => "Ya",
        "sinyal_seluler" => "Sangat Baik",
        "catatan" => "Infrastruktur di wilayah ini sangat baik dan mendukung kebutuhan masyarakat.",
      ],
      "land_cover_observasi" => [
        "periode_pengecekan" => "April 2025",
        "kategori_area" => "Pertanian",
        "penggunaan_pertanian" => "Padi",
        "penggunaan_lainnya" => "Pemukiman",
        "persentase_tutupan" => "70%",
        "catatan" => "Mayoritas lahan digunakan untuk pertanian padi dengan beberapa area pemukiman di sekitarnya.",
      ],
      "topografi_observasi" => [
        "periode_pengecekan" => "April 2025",
        "lanskap" => "Datar",
        "fitur_tambahan" => "Terdapat lembah kecil",
        "elevasi_mdpl" => "200 mdpl",
        "kemiringan_derajat" => "1.5",
        "rawan_erosi" => "Tidak Rawan",
        "arah_lereng" => "Utara",
        "catatan" => "Topografi datar dengan kemiringan yang rendah, cocok untuk pertanian dan tidak rawan erosi.",
      ],
      "pohon_observasi" => [
        "periode_pengecekan" => "April 2025",
        "nama_pohon" => "Mangga",
        "nama_latin" => "Mangifera indica",
        "fungsi_pohon" => "Penghasil buah dan pohon bayangan",
        "jumlah_pohon" => "5",
        "diameter_rata2_cm" => "30",
        "tinggi_rata2_m" => "4",
        "kondisi" => "Baik",
        "catatan" => "Pohon mangga dalam kondisi baik dan sehat.",
      ],
      "bank_benih" => [
        [
          "nomor_aksesi" => "842342345",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Panamaea americana",
          "nama_ilmiah" => "American Panamaea",
          "famili_tanaman" => "Benih",
          "provenance" => "Amerika",
          "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
          "tanggal_masuk" => "12 Maret 2025",
          "jumlah_stok" => "12",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "8%",
          "viabilitas_persen" => "90%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "12 Maret 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih berkualitas tinggi",
          "jumlah_ditanam" => "12",
          "satuan" => "PCS",
          "jumlah_hidup" => "11",
          "jumlah_mati" => "1",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
        [
          "nomor_aksesi" => "742342346",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Kacang Tanah",
          "nama_ilmiah" => "Arachis hypogaea",
          "famili_tanaman" => "Benih",
          "provenance" => "Indonesia",
          "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
          "tanggal_masuk" => "15 April 2025",
          "jumlah_stok" => "20",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "8%",
          "viabilitas_persen" => "95%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "15 April 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih kacang tanah berkualitas tinggi",
          "jumlah_ditanam" => "12",
          "satuan" => "PCS",
          "jumlah_hidup" => "11",
          "jumlah_mati" => "1",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
      ],
    ],
    [
      "id_kaleka" => 3,
      "nama_kaleka" => "Kaleka 3",
      "keterangan" => "",
      "petani" => [
        "nama_lengkap" => "Agung Hapsah",
        "nama_panggilan" => "Agung",
        "nik" => "624535345444343",
        "no_kk" => "1234567890123456",
        "jenis_kelamin" => "Pria",
        "tanggal_lahir" => "23 April 1990",
        "umur" => "35 tahun",
        "nomor_hp" => "082134567833",
        "alamat" => "Jalan Raya Tumbang Samui No. 456",
        "foto" => "images/petani3.jpeg",
        "status_petani" => "Aktif",
        "petani_kelompok" => [
          [
            "nama_kelompok_tani" => "Kelompok 2",
            "kategori_kelompok" => "Kategori 2",
            "deskripsi" => "Kelompok tani yang Aktif dalam kegiatan pertanian di wilayah Kaleka 2",
            "alamat" => "Jalan Raya Tumbang Samui No. 456",
            "akses_perjalanan" => "Mudah",
            "kondisi_jalan" => "Baik",
            "tahun_bentuk" => "2020",
            "nomor_sk" => "SK-002/2020",
            "tanggal_sk" => "15 Mei 2020",
            "status_kelompok" => "Aktif",
            "jabatan_kelompok" => "Ketua",
            "tahun_gabung" => "2025",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
        ],
      ],
      "desa" => [
        "nama_desa" => "Tumbang Samui",
        "tipe_wilayah" => "kelurahan",
        "nama_kecamatan" => "Manuhing Raya",
        "nama_kabupaten" => "Gunung Mas",
        "tipe" => "kabupaten",
        "nama_provinsi" => "Kalimantan Tengah",
        "kode_pos" => "74562",
      ],
      "tanah" => [
        "nama_lahan" => "Lahan keluarga",
        "legalitas_lahan" => "Belum Ada",
        "status_kawasan" => "Kaleka",
        "luas_ha" => "±1 Ha",
        "centroid_lat" => "-1.2963889949807585",
        "centroid_lng" => "113.31212997436525",
        "geom_area" => [
          [-1.2963889949807585, 113.31212997436525],
          [-1.2962710079893713, 113.31307411193849],
          [-1.297139821160766, 113.31357836723329],
          [-1.2970861907267195, 113.31277370452882],
        ],
        "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
        "keterangan" => "Lahan milik keluarga Agung Hapsah yang digunakan untuk pertanian dan kegiatan lainnya.",
        "sudah_validasi" => "Sudah",
        "tanggal_validasi" => "15 April 2025",
        "sejarah" => "Lahan keluarga",
      ],
      "perairan_observasi" => [
        "periode_pengecekan" => "April 2025",
        "warna_air" => "Biru",
        "jenis_palung" => "Palung alami",
        "kecepatan_aliran" => "Sedang",
        "kedalaman_cm" => "120",
        "lebar_m" => "30",
        "debit_lps" => "500",
        "ph" => "7.5",
        "kekeruhan_ntu" => "10",
        "catatan" => "Perairan dalam kondisi baik dengan aliran sedang dan kedalaman yang cukup untuk pertanian.",
      ],
      "infrastruktur_observasi" => [
        "periode_pengecekan" => "April 2025",
        "akses_perjalanan" => "Mudah",
        "kondisi_jalan" => "Baik",
        "jarak_ke_jalan_km" => "0.5",
        "ada_jembatan" => "Ya",
        "ada_listrik" => "Ya",
        "ada_internet" => "Ya",
        "sinyal_seluler" => "Sangat Baik",
        "catatan" => "Infrastruktur di wilayah ini sangat baik dan mendukung kebutuhan masyarakat.",
      ],
      "land_cover_observasi" => [
        "periode_pengecekan" => "April 2025",
        "kategori_area" => "Pertanian",
        "penggunaan_pertanian" => "Padi",
        "penggunaan_lainnya" => "Pemukiman",
        "persentase_tutupan" => "70%",
        "catatan" => "Mayoritas lahan digunakan untuk pertanian padi dengan beberapa area pemukiman di sekitarnya.",
      ],
      "topografi_observasi" => [
        "periode_pengecekan" => "April 2025",
        "lanskap" => "Datar",
        "fitur_tambahan" => "Terdapat lembah kecil",
        "elevasi_mdpl" => "200 mdpl",
        "kemiringan_derajat" => "1.5",
        "rawan_erosi" => "Tidak Rawan",
        "arah_lereng" => "Utara",
        "catatan" => "Topografi datar dengan kemiringan yang rendah, cocok untuk pertanian dan tidak rawan erosi.",
      ],
      "pohon_observasi" => [
        "periode_pengecekan" => "April 2025",
        "nama_pohon" => "Mangga",
        "nama_latin" => "Mangifera indica",
        "fungsi_pohon" => "Penghasil buah dan pohon bayangan",
        "jumlah_pohon" => "5",
        "diameter_rata2_cm" => "30",
        "tinggi_rata2_m" => "4",
        "kondisi" => "Baik",
        "catatan" => "Pohon mangga dalam kondisi baik dan sehat.",
      ],
      "bank_benih" => [
        [
          "nomor_aksesi" => "842342345",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Panamaea americana",
          "nama_ilmiah" => "American Panamaea",
          "famili_tanaman" => "Benih",
          "provenance" => "Amerika",
          "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
          "tanggal_masuk" => "12 Maret 2025",
          "jumlah_stok" => "12",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "8%",
          "viabilitas_persen" => "90%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "12 Maret 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih berkualitas tinggi",
          "jumlah_ditanam" => "12",
          "satuan" => "PCS",
          "jumlah_hidup" => "11",
          "jumlah_mati" => "1",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
        [
          "nomor_aksesi" => "742342346",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Kacang Tanah",
          "nama_ilmiah" => "Arachis hypogaea",
          "famili_tanaman" => "Benih",
          "provenance" => "Indonesia",
          "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
          "tanggal_masuk" => "15 April 2025",
          "jumlah_stok" => "20",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "8%",
          "viabilitas_persen" => "95%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "15 April 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih kacang tanah berkualitas tinggi",
          "jumlah_ditanam" => "12",
          "satuan" => "PCS",
          "jumlah_hidup" => "11",
          "jumlah_mati" => "1",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
      ],
    ],
    [
      "id_kaleka" => 4,
      "nama_kaleka" => "Kaleka 4",
      "keterangan" => "",
      "petani" => [
        "nama_lengkap" => "Gusti Mahendar",
        "nama_panggilan" => "Hendar",
        "nik" => "624535345444343",
        "no_kk" => "1234567890123456",
        "jenis_kelamin" => "Pria",
        "tanggal_lahir" => "23 April 1990",
        "umur" => "35 tahun",
        "nomor_hp" => "082134567833",
        "alamat" => "Jalan Raya Tumbang Samui No. 456",
        "foto" => "images/petani4.jpeg",
        "status_petani" => "Aktif",
        "petani_kelompok" => [
          [
            "nama_kelompok_tani" => "Kelompok 1",
            "kategori_kelompok" => "Kategori 1",
            "deskripsi" => "Kelompok tani yang Aktif dalam kegiatan pertanian di wilayah Kaleka 2",
            "alamat" => "Jalan Raya Tumbang Samui No. 456",
            "akses_perjalanan" => "Mudah",
            "kondisi_jalan" => "Baik",
            "tahun_bentuk" => "2020",
            "nomor_sk" => "SK-002/2020",
            "tanggal_sk" => "15 Mei 2020",
            "status_kelompok" => "Aktif",
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2025",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
          [
            "nama_kelompok_tani" => "Kelompok 2",
            "kategori_kelompok" => "Kategori 2",
            "deskripsi" => "Kelompok tani yang baru dibentuk dan sedang dalam tahap pengembangan di wilayah Kaleka 1",
            "alamat" => "Jalan Raya Tumbang Samui No. 456",
            "akses_perjalanan" => "Mudah",
            "kondisi_jalan" => "Baik",
            "tahun_bentuk" => "2021",
            "nomor_sk" => "SK-002/2021",
            "tanggal_sk" => "15 April 2021",
            "status_kelompok" => "Aktif",
            "jabatan_kelompok" => "Anggota",
            "tahun_gabung" => "2026",
            "tanggal_keluar" => "2024",
            "is_pengurus" => "1",
            "is_active" => "1"
          ],
        ],
      ],
      "desa" => [
        "nama_desa" => "Tumbang Samui",
        "tipe_wilayah" => "kelurahan",
        "nama_kecamatan" => "Manuhing Raya",
        "nama_kabupaten" => "Gunung Mas",
        "tipe" => "kabupaten",
        "nama_provinsi" => "Kalimantan Tengah",
        "kode_pos" => "74562",
      ],
      "tanah" => [
        "nama_lahan" => "Lahan keluarga",
        "legalitas_lahan" => "Belum Ada",
        "status_kawasan" => "Kaleka",
        "luas_ha" => "±1 Ha",
        "centroid_lat" => "-1.2963889949807585",
        "centroid_lng" => "113.31212997436525",
        "geom_area" => [
          [-1.2950160551044538, 113.31307411193849],
          [-1.2960028557157703, 113.31398606300355],
          [-1.296027911195035, 113.31515550613405],
          [-1.2953005480171402, 113.31549882888795],
          [-1.2947693548915822, 113.31483364105226],
        ],
        "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
        "keterangan" => "Lahan milik keluarga Gusti Mahendar yang digunakan untuk pertanian dan kegiatan lainnya.",
        "sudah_validasi" => "Sudah",
        "tanggal_validasi" => "15 April 2025",
        "sejarah" => "Lahan keluarga",
      ],
      "perairan_observasi" => [
        "periode_pengecekan" => "April 2025",
        "warna_air" => "Biru",
        "jenis_palung" => "Palung alami",
        "kecepatan_aliran" => "Sedang",
        "kedalaman_cm" => "120",
        "lebar_m" => "30",
        "debit_lps" => "500",
        "ph" => "7.5",
        "kekeruhan_ntu" => "10",
        "catatan" => "Perairan dalam kondisi baik dengan aliran sedang dan kedalaman yang cukup untuk pertanian.",
      ],
      "infrastruktur_observasi" => [
        "periode_pengecekan" => "April 2025",
        "akses_perjalanan" => "Mudah",
        "kondisi_jalan" => "Baik",
        "jarak_ke_jalan_km" => "0.5",
        "ada_jembatan" => "Ya",
        "ada_listrik" => "Ya",
        "ada_internet" => "Ya",
        "sinyal_seluler" => "Sangat Baik",
        "catatan" => "Infrastruktur di wilayah ini sangat baik dan mendukung kebutuhan masyarakat.",
      ],
      "land_cover_observasi" => [
        "periode_pengecekan" => "April 2025",
        "kategori_area" => "Pertanian",
        "penggunaan_pertanian" => "Padi",
        "penggunaan_lainnya" => "Pemukiman",
        "persentase_tutupan" => "70%",
        "catatan" => "Mayoritas lahan digunakan untuk pertanian padi dengan beberapa area pemukiman di sekitarnya.",
      ],
      "topografi_observasi" => [
        "periode_pengecekan" => "April 2025",
        "lanskap" => "Datar",
        "fitur_tambahan" => "Terdapat lembah kecil",
        "elevasi_mdpl" => "200 mdpl",
        "kemiringan_derajat" => "1.5",
        "rawan_erosi" => "Tidak Rawan",
        "arah_lereng" => "Utara",
        "catatan" => "Topografi datar dengan kemiringan yang rendah, cocok untuk pertanian dan tidak rawan erosi.",
      ],
      "pohon_observasi" => [
        "periode_pengecekan" => "April 2025",
        "nama_pohon" => "Mangga",
        "nama_latin" => "Mangifera indica",
        "fungsi_pohon" => "Penghasil buah dan pohon bayangan",
        "jumlah_pohon" => "5",
        "diameter_rata2_cm" => "30",
        "tinggi_rata2_m" => "4",
        "kondisi" => "Baik",
        "catatan" => "Pohon mangga dalam kondisi baik dan sehat.",
      ],
      "bank_benih" => [
        [
          "nomor_aksesi" => "842342345",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Parei Tampui",
          "nama_ilmiah" => "Oryza sativa",
          "famili_tanaman" => "Benih",
          "provenance" => "Amerika",
          "tipe_penyimpanan_benih" => "Gelas Kaca",
          "tanggal_masuk" => "12 Maret 2025",
          "jumlah_stok" => "12",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "8%",
          "viabilitas_persen" => "90%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "12 Maret 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih berkualitas tinggi",
          "jumlah_ditanam" => "30",
          "satuan" => "PCS",
          "jumlah_hidup" => "25",
          "jumlah_mati" => "5",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
        [
          "nomor_aksesi" => "742342346",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Kacang Tanah",
          "nama_ilmiah" => "Arachis hypogaea",
          "famili_tanaman" => "Benih",
          "provenance" => "Indonesia",
          "tipe_penyimpanan_benih" => "Gelas Kaca",
          "tanggal_masuk" => "15 April 2025",
          "jumlah_stok" => "20",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "5%",
          "viabilitas_persen" => "95%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "15 April 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih kacang tanah berkualitas tinggi",
          "jumlah_ditanam" => "35",
          "satuan" => "PCS",
          "jumlah_hidup" => "30",
          "jumlah_mati" => "5",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
        [
          "nomor_aksesi" => "842342345",
          "nama_negara" => "Indonesia",
          "nama_lokal" => "Singkong",
          "nama_ilmiah" => "Manihot esculenta",
          "famili_tanaman" => "Benih",
          "provenance" => "Amerika",
          "tipe_penyimpanan_benih" => "Salipi",
          "tanggal_masuk" => "12 Maret 2025",
          "jumlah_stok" => "16",
          "satuan_stok" => "PCS",
          "kadar_air_persen" => "7%",
          "viabilitas_persen" => "90%",
          "ketinggian_mdpl" => "200 mdpl",
          "masa_berlaku_sampai" => "12 Maret 2030",
          "lokasi_penyimpanan" => "Gudang Benih",
          "titik_koleksi_lat" => "-1.2716",
          "titik_koleksi_lng" => "113.3208",
          "catatan" => "Benih berkualitas tinggi",
          "jumlah_ditanam" => "25",
          "satuan" => "PCS",
          "jumlah_hidup" => "18",
          "jumlah_mati" => "7",
          "tinggi_rata2_cm" => "5",
          "diameter_rata2_cm" => "2",
          "gambar_benih" => "images/benih1.png",
          "monitoring_penanaman" => [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
          ],
        ],
      ],
    ],
  ],

  "benih" => [
    [
      "bank_benih" => [
        "id_bank_benih" => "1",
        "nomor_aksesi" => "842342345",
        "nama_negara" => "Indonesia",
        "nama_lokal" => "Panamaea americana",
        "nama_ilmiah" => "American Panamaea",
        "famili_tanaman" => "Benih",
        "provenance" => "Amerika",
        "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
        "tanggal_masuk" => "12 Maret 2025",
        "jumlah_stok" => "12",
        "satuan_stok" => "PCS",
        "kadar_air_persen" => "8%",
        "viabilitas_persen" => "90%",
        "ketinggian_mdpl" => "200 mdpl",
        "masa_berlaku_sampai" => "12 Maret 2030",
        "lokasi_penyimpanan" => "Gudang Benih",
        "titik_koleksi_lat" => "-1.2716",
        "titik_koleksi_lng" => "113.3208",
        "catatan" => "Benih berkualitas tinggi",
        "jumlah_ditanam" => "12",
        "satuan" => "PCS",
        "jumlah_hidup" => "11",
        "jumlah_mati" => "1",
        "tinggi_rata2_cm" => "5",
        "diameter_rata2_cm" => "2",
        "gambar_benih" => "images/benih1.png",
        "monitoring_penanaman" => [
          [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "April 2025",
            "tanggal_tanam" => "15 April 2025",
            "tanggal_monitoring" => "15 April 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
            "tanah" => [
              "nama_lahan" => "Lahan keluarga",
              "legalitas_lahan" => "Belum Ada",
              "status_kawasan" => "Benih",
              "luas_ha" => "±1 Ha",
              "centroid_lat" => "-1.2963889949807585",
              "centroid_lng" => "113.31212997436525",
              "geom_area" => [
                [-1.2975327059542199, 113.31180274486542],
                [-1.2977686798138561, 113.31181883811952],
                [-1.2977686798138561, 113.31230163574219],
                [-1.2975151084709131, 113.31226944923402],
              ],
              "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
              "keterangan" => "Lahan milik keluarga Gusti Mahendar yang digunakan untuk pertanian dan kegiatan lainnya.",
              "sudah_validasi" => "Sudah",
              "tanggal_validasi" => "15 April 2025",
              "sejarah" => "Lahan keluarga",
              "petani" => [
                "nama_lengkap" => "Jito Susilo",
                "nama_panggilan" => "Jito",
                "gender" => "Pria",
                "tanggal_lahir" => "20 Maret 1991",
                "umur" => "34 tahun",
                "kelompok" => "Kelompok 1",
                "desa" => "Tumbang Samui",
                "kecamatan" => "Manuhing Raya",
                "foto" => "images/petani1.jpeg",
              ],
            ],
          ],
          [
            "nama_tipe_penanaman" => "Penanaman Pohon",
            "progress_status_monitoring" => "Berjalan",
            "periode_pengecekan" => "Juni 2025",
            "tanggal_tanam" => "15 Juni 2025",
            "tanggal_monitoring" => "15 Juni 2025",
            "luas_tanam_ha" => "0.5 Ha",
            "survival_rate_persen" => "90%",
            "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
            "tanah" => [
              "nama_lahan" => "Lahan keluarga",
              "legalitas_lahan" => "Belum Ada",
              "status_kawasan" => "Benih",
              "luas_ha" => "±1 Ha",
              "centroid_lat" => "-1.2963889949807585",
              "centroid_lng" => "113.31212997436525",
              "geom_area" => [
                [-1.2975327059542199, 113.31180274486542],
                [-1.2977686798138561, 113.31181883811952],
                [-1.2977686798138561, 113.31230163574219],
                [-1.2975151084709131, 113.31226944923402],
              ],
              "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
              "keterangan" => "Lahan milik keluarga Gusti Mahendar yang digunakan untuk pertanian dan kegiatan lainnya.",
              "sudah_validasi" => "Sudah",
              "tanggal_validasi" => "15 April 2025",
              "sejarah" => "Lahan keluarga",
              "petani" => [
                "nama_lengkap" => "Jito Susilo",
                "nama_panggilan" => "Jito",
                "gender" => "Pria",
                "tanggal_lahir" => "20 Maret 1991",
                "umur" => "34 tahun",
                "kelompok" => "Kelompok 1",
                "desa" => "Tumbang Samui",
                "kecamatan" => "Manuhing Raya",
                "foto" => "images/petani1.jpeg",
              ],
            ],
          ],
        ],
        "tanah" => [
          "nama_lahan" => "Lahan keluarga",
          "legalitas_lahan" => "Belum Ada",
          "status_kawasan" => "Benih",
          "luas_ha" => "±1 Ha",
          "centroid_lat" => "-1.2963889949807585",
          "centroid_lng" => "113.31212997436525",
          "geom_area" => [
            [-1.2975327059542199, 113.31180274486542],
            [-1.2977686798138561, 113.31181883811952],
            [-1.2977686798138561, 113.31230163574219],
            [-1.2975151084709131, 113.31226944923402],
          ],
          "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
          "keterangan" => "Lahan milik keluarga Gusti Mahendar yang digunakan untuk pertanian dan kegiatan lainnya.",
          "sudah_validasi" => "Sudah",
          "tanggal_validasi" => "15 April 2025",
          "sejarah" => "Lahan keluarga",
          "petani" => [
            "nama_lengkap" => "Jito Susilo",
            "nama_panggilan" => "Jito",
            "gender" => "Pria",
            "tanggal_lahir" => "20 Maret 1991",
            "umur" => "34 tahun",
            "kelompok" => "Kelompok 1",
            "desa" => "Tumbang Samui",
            "kecamatan" => "Manuhing Raya",
            "foto" => "images/petani1.jpeg",
          ],
        ],
      ],
    ],
  ],

  // "benih" => [
  //   [
  //     "monitoring_penanaman" => [
  //       "nama_tipe_penanaman" => "Penanaman Pohon",
  //       "progress_status_monitoring" => "Berjalan",
  //       "periode_pengecekan" => "April 2025",
  //       "tanggal_tanam" => "15 April 2025",
  //       "tanggal_monitoring" => "15 April 2025",
  //       "luas_tanam_ha" => "0.5 Ha",
  //       "survival_rate_persen" => "90%",
  //       "catatan" => "Penanaman pohon mangga berjalan dengan baik dan tingkat survival rate yang tinggi.",
  //       "bank_benih" => [
  //         [
  //           "nomor_aksesi" => "842342345",
  //           "nama_negara" => "Indonesia",
  //           "nama_lokal" => "Panamaea americana",
  //           "nama_ilmiah" => "American Panamaea",
  //           "famili_tanaman" => "Benih",
  //           "provenance" => "Amerika",
  //           "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
  //           "tanggal_masuk" => "12 Maret 2025",
  //           "jumlah_stok" => "12",
  //           "satuan_stok" => "PCS",
  //           "kadar_air_persen" => "8%",
  //           "viabilitas_persen" => "90%",
  //           "ketinggian_mdpl" => "200 mdpl",
  //           "masa_berlaku_sampai" => "12 Maret 2030",
  //           "lokasi_penyimpanan" => "Gudang Benih",
  //           "titik_koleksi_lat" => "-1.2716",
  //           "titik_koleksi_lng" => "113.3208",
  //           "catatan" => "Benih berkualitas tinggi",
  //           "jumlah_ditanam" => "12",
  //           "satuan" => "PCS",
  //           "jumlah_hidup" => "11",
  //           "jumlah_mati" => "1",
  //           "tinggi_rata2_cm" => "5",
  //           "diameter_rata2_cm" => "2",
  //           "gambar_benih" => "images/benih1.png",
  //         ],
  //         [
  //           "nomor_aksesi" => "742342346",
  //           "nama_negara" => "Indonesia",
  //           "nama_lokal" => "Kacang Tanah",
  //           "nama_ilmiah" => "Arachis hypogaea",
  //           "famili_tanaman" => "Benih",
  //           "provenance" => "Indonesia",
  //           "tipe_penyimpanan_benih" => "Ruang Penyimpanan",
  //           "tanggal_masuk" => "15 April 2025",
  //           "jumlah_stok" => "20",
  //           "satuan_stok" => "PCS",
  //           "kadar_air_persen" => "8%",
  //           "viabilitas_persen" => "95%",
  //           "ketinggian_mdpl" => "200 mdpl",
  //           "masa_berlaku_sampai" => "15 April 2030",
  //           "lokasi_penyimpanan" => "Gudang Benih",
  //           "titik_koleksi_lat" => "-1.2716",
  //           "titik_koleksi_lng" => "113.3208",
  //           "catatan" => "Benih kacang tanah berkualitas tinggi",
  //           "jumlah_ditanam" => "12",
  //           "satuan" => "PCS",
  //           "jumlah_hidup" => "11",
  //           "jumlah_mati" => "1",
  //           "tinggi_rata2_cm" => "5",
  //           "diameter_rata2_cm" => "2",
  //           "gambar_benih" => "images/benih1.png",
  //         ],
  //       ],
  //       "tanah" => [
  //         "nama_lahan" => "Lahan keluarga",
  //         "legalitas_lahan" => "Belum Ada",
  //         "status_kawasan" => "Benih",
  //         "luas_ha" => "±1 Ha",
  //         "centroid_lat" => "-1.2963889949807585",
  //         "centroid_lng" => "113.31212997436525",
  //         "geom_area" => [
  //           [-1.2975327059542199, 113.31180274486542],
  //           [-1.2977686798138561, 113.31181883811952],
  //           [-1.2977686798138561, 113.31230163574219],
  //           [-1.2975151084709131, 113.31226944923402],
  //         ],
  //         "alamat_lokasi" => "Tumbang Samui, Manuhing Raya",
  //         "keterangan" => "Lahan milik keluarga Gusti Mahendar yang digunakan untuk pertanian dan kegiatan lainnya.",
  //         "sudah_validasi" => "Sudah",
  //         "tanggal_validasi" => "15 April 2025",
  //         "sejarah" => "Lahan keluarga",
  //         "petani" => [
  //           "nama_lengkap" => "Jito Susilo",
  //           "nama_panggilan" => "Jito",
  //           "gender" => "Pria",
  //           "tanggal_lahir" => "20 Maret 1991",
  //           "umur" => "34 tahun",
  //           "kelompok" => "Kelompok 1",
  //           "desa" => "Tumbang Samui",
  //           "kecamatan" => "Manuhing Raya",
  //           "foto" => "images/petani1.jpeg",
  //           "petani_kelompoknya" => [
  //             [
  //               "kategori" => "Kategori 1",
  //               "jabatan_kelompok" => "Ketua",
  //               "tahun_gabung" => "2024",
  //               "sudah_validasi" => "Sudah"
  //             ],
  //             [
  //               "kategori" => "Kategori 2",
  //               "jabatan_kelompok" => "Anggota",
  //               "tahun_gabung" => "2024",
  //               "sudah_validasi" => "Sudah"
  //             ],
  //             [
  //               "kategori" => "Kategori 3",
  //               "jabatan_kelompok" => "Anggota",
  //               "tahun_gabung" => "2024",
  //               "sudah_validasi" => "Sudah"
  //             ]
  //           ]
  //         ],
  //       ],
  //     ],
  //   ],
  // ],
], JSON_PRETTY_PRINT);

